[build-system]
requires = ["setuptools", "wheel", "Cython>=0.29.22,<3", "numpy", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "python-optix"
description = "Python bindings to the OptiX raytracing engine by nvidia."
authors = [
    { name = "Felix Igelbrink", email = "felix.igelbrink@dfki.de" }
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Environment :: GPU :: NVIDIA CUDA",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]
dependencies = [
    'numpy'
]
dynamic = ["version"]


[tool.setuptools.packages.find]
include = [
    'optix'
]

[project.optional-dependencies]
cupy = ["cupy"] # regular cupy (e.g. from conda)
cupy-cuda12x = ["cupy-cuda12x"] # pip installable cupy
examples = ["pillow", "pyopengl", "pyglfw", "pyimgui", "imageio"] # additional deps for the examples

[project.urls]
Homepage = "https://github.com/mortacious/python-optix"
Issues = "https://github.com/mortacious/python-optix/issues"


[tool.setuptools]
license-files = ["../LICENSE"]


[tool.setuptools_scm]
write_to = "optix/_version.py"
version_scheme = "release-branch-semver"